# https://man.archlinux.org/man/mkinitcpio.8
# https://wiki.archlinux.org/title/Mkinitcpio

MODULES=()
BINARIES=()
FILES=()
HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont block filesystems resume fsck)
ALL_kver="/boot/vmlinuz-linux"
PRESETS=('default')

default_uki="/boot/EFI/Linux/arch-linux.efi"
default_options=""
fallback_uki="/boot/EFI/Linux/arch-linux-fallback.efi"
