# Docker Socket Proxy for Windows Access
# Exposes Docker daemon to Windows via TCP
#
# Usage: docker compose -f /opt/cozy/docker-proxy.yaml up -d
# Windows: docker context create wsl --docker "host=tcp://localhost:2375"
# TODO: move to /opt/copzy/docker

services:
  # Traefik for routing (optional, provides metrics/dashboard)
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.docker.address=:2376"
      - "--log.level=INFO"
    ports:
      - "2376:2376"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxy

  # Socat proxy - exposes Docker socket on TCP 2375
  docker-socket-proxy:
    image: alpine/socat
    container_name: docker-socket-proxy
    restart: unless-stopped
    command: >
      tcp-listen:2375,fork,reuseaddr
      unix-connect:/var/run/docker.sock
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.docker.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.docker.entrypoints=docker"
      - "traefik.tcp.routers.docker.tls=false"
      - "traefik.tcp.services.docker.loadbalancer.server.port=2375"
    networks:
      - docker-proxy

networks:
  docker-proxy:
    driver: bridge
