if [ -n "${__ETC_ZSH_ZPROFILE_SOURCED}" ]; then
    return 0
fi

# TODO: ensure /etc/profile.d and /etc/profile are compat w zsh and bash
#emulate bash -Lc 'source /etc/profile'
source /etc/profile


__ETC_ZSH_ZPROFILE_SOURCED=1
export __ETC_ZSH_ZPROFILE_SOURCED
