src = ["src", "tests"]
builtins = ["__salt__", "__grains__", "__pillar__", "__opts__"]
lint.select = ["E", "F", "I"]
lint.ignore = []
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]
per-file-ignores = { "tests/**/*.py" = [
  "E501",
], "scripts/**/*.py" = [
  "E501",
], "srv/salt/_modules/*.py" = [
  "E501",
], "srv/salt/_grains/*.py" = [
  "E501",
] }
