extends: relaxed

rules:
  line-length:
    max: 120
  document-start: disable
  truthy: disable
  new-lines:
    type: unix
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  comments-indentation: disable
