#!/bin/bash
# install-linux-minion.sh
# Installs Salt Minion on Linux and configures it to connect to the Salt Master
#
# Usage:
#   sudo ./install-linux-minion.sh --master <master-ip-or-hostname>
#   sudo ./install-linux-minion.sh --master salt-master --minion-id my-linux-server
#
# Requires: root/sudo privileges

set -e

# Default values
MASTER="salt-master"
MINION_ID=$(hostname -f)
SALT_VERSION="latest"
ROLES="server"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --master|-m)
            MASTER="$2"
            shift 2
            ;;
        --minion-id|-i)
            MINION_ID="$2"
            shift 2
            ;;
        --version|-v)
            SALT_VERSION="$2"
            shift 2
            ;;
        --roles|-r)
            ROLES="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --master, -m       Salt Master hostname or IP (default: salt-master)"
            echo "  --minion-id, -i    Minion ID (default: $(hostname -f))"
            echo "  --version, -v      Salt version (default: latest)"
            echo "  --roles, -r        Comma-separated roles (default: server)"
            echo "                     Use 'kvm-host' to enable KVM packages"
            echo "  --help, -h         Show this help message"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Check for root
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

echo "=== Salt Minion Installation ==="
echo "Master: $MASTER"
echo "Minion ID: $MINION_ID"
echo "Salt Version: $SALT_VERSION"
echo ""

# Detect OS
if [ -f /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    OS=$ID
    VER=$VERSION_ID
else
    echo "Error: Cannot detect OS. /etc/os-release not found."
    exit 1
fi

# Check if Salt is already installed
if command -v salt-minion >/dev/null 2>&1; then
    echo "Salt Minion is already installed."
    salt-minion --version
    echo ""
    read -p "Do you want to reconfigure? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Exiting without changes."
        exit 0
    fi
    echo "Stopping salt-minion service..."
    systemctl stop salt-minion || service salt-minion stop || true
fi

# Install Salt Minion based on OS
case "$OS" in
    ubuntu|debian|kali)
        echo "Installing Salt Minion on Debian/Ubuntu/Kali..."

        # Clean up broken Docker repository configurations before apt-get update
        # WSL may have pre-existing repo configs pointing to wrong OS path
        rm -f /etc/apt/sources.list.d/docker.list 2>/dev/null || true

        # Install prerequisites
        apt-get update || apt-get update --allow-releaseinfo-change
        apt-get install -y curl ca-certificates

        # Add Salt repository (no GPG verification - trusted repository)
        echo "deb [arch=amd64 trusted=yes] https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" > \
            /etc/apt/sources.list.d/salt.list

        apt-get update
        apt-get install -y salt-minion
        ;;

    rhel|centos|rocky|almalinux|fedora)
        echo "Installing Salt Minion on RHEL/CentOS/Rocky/Fedora..."

        # Add Salt repository (no GPG verification - trusted repository)
        cat > /etc/yum.repos.d/salt.repo <<EOF
[salt-repo]
name=Salt repo for RHEL/CentOS/Rocky/Fedora
baseurl=https://packages.broadcom.com/artifactory/saltproject-rpm/
enabled=1
gpgcheck=0
EOF

        yum install -y salt-minion
        ;;

    *)
        echo "Error: Unsupported OS: $OS"
        echo "  version: $VER"
        echo "Please install Salt Minion manually: https://docs.saltproject.io/salt/install-guide/en/latest/"
        exit 1
        ;;
esac

# Configure minion
echo "Configuring Salt Minion..."
mkdir -p /etc/salt/minion.d

# Convert comma-separated roles to YAML list
ROLES_YAML=""
IFS=',' read -ra ROLE_ARRAY <<< "$ROLES"
for role in "${ROLE_ARRAY[@]}"; do
    ROLES_YAML="${ROLES_YAML}    - ${role}\n"
done

cat > /etc/salt/minion.d/99-custom.conf <<EOF
# Salt Minion Configuration
# Generated by install-linux-minion.sh

master: $MASTER
id: $MINION_ID

# Grains (custom facts about this minion)
grains:
  roles:
$(echo -e "$ROLES_YAML")
  environment: development

# File client settings
file_client: remote

# Logging
log_level: info
EOF

# Enable and start service
echo "Starting salt-minion service..."
systemctl enable salt-minion
systemctl restart salt-minion

# Verify
sleep 3
if systemctl is-active --quiet salt-minion; then
    echo ""
    echo "=== Installation Complete ==="
    echo "Salt Minion is running."
    echo ""
    echo "Next steps:"
    echo "  1. On the Salt Master, accept the minion key:"
    echo "     salt-key -a $MINION_ID"
    echo ""
    echo "  2. Test connectivity:"
    echo "     salt '$MINION_ID' test.ping"
    echo ""
else
    echo "Error: Salt Minion service failed to start."
    echo "Check logs: journalctl -u salt-minion -n 50"
    exit 1
fi
