# install-windows-minion.ps1
# Installs Salt Minion on Windows and configures it to connect to the Salt Master
#
# Usage:
#   .\install-windows-minion.ps1 -Master <master-ip-or-hostname>
#   .\install-windows-minion.ps1 -Master salt-master -MinionId my-windows-pc
#
# Requires: Administrator privileges

param(
    [Parameter(Mandatory=$false)]
    [string]$Master = "salt-master",

    [Parameter(Mandatory=$false)]
    [string]$MinionId = $env:COMPUTERNAME.ToLower(),

    [Parameter(Mandatory=$false)]
    [string]$SaltVersion = "3007.10"
)

$ErrorActionPreference = "Stop"

# Check for admin privileges
if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Write-Error "This script requires Administrator privileges. Please run as Administrator."
    exit 1
}

Write-Host "=== Salt Minion Installation ===" -ForegroundColor Cyan
Write-Host "Master: $Master"
Write-Host "Minion ID: $MinionId"
Write-Host "Salt Version: $SaltVersion"
Write-Host ""

# Check if Salt is already installed
$saltService = Get-Service -Name "salt-minion" -ErrorAction SilentlyContinue
if ($saltService) {
    Write-Host "Salt Minion is already installed." -ForegroundColor Yellow
    Write-Host "Service Status: $($saltService.Status)"

    $response = Read-Host "Do you want to reconfigure? (y/N)"
    if ($response -ne 'y' -and $response -ne 'Y') {
        Write-Host "Exiting without changes."
        exit 0
    }

    Write-Host "Stopping salt-minion service..."
    Stop-Service -Name "salt-minion" -Force
}

# Download and install Salt Minion if not present
$saltExe = "C:\salt\salt-minion.exe"
if (-NOT (Test-Path $saltExe)) {
    Write-Host "Downloading Salt Minion..." -ForegroundColor Green

    # Salt download URL (Broadcom Artifactory - requires version subdirectory)
    $downloadUrl = "https://packages.broadcom.com/artifactory/saltproject-generic/windows/$SaltVersion/Salt-Minion-$SaltVersion-Py3-AMD64-Setup.exe"
    $installerPath = "$env:TEMP\salt-minion-setup.exe"

    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $downloadUrl -OutFile $installerPath -UseBasicParsing
    }
    catch {
        Write-Error "Failed to download Salt Minion: $_"
        Write-Host "Try downloading manually from: https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/windows.html"
        exit 1
    }

    Write-Host "Installing Salt Minion..." -ForegroundColor Green
    $installArgs = "/S /master=$Master /minion-name=$MinionId"
    Start-Process -FilePath $installerPath -ArgumentList $installArgs -Wait

    Remove-Item $installerPath -Force -ErrorAction SilentlyContinue
}

# Configure minion
$minionConfig = "C:\salt\conf\minion"
Write-Host "Configuring Salt Minion..." -ForegroundColor Green

$configContent = @"
# Salt Minion Configuration
# Generated by install-win-minion.ps1

master: $Master
id: $MinionId

# Grains (custom facts about this minion)
grains:
  roles:
    - workstation
  environment: development

# File client settings
file_client: remote

# Logging
log_level: info
"@

Set-Content -Path $minionConfig -Value $configContent -Force

# Start the service
Write-Host "Starting salt-minion service..." -ForegroundColor Green
Start-Service -Name "salt-minion"

# Verify
Start-Sleep -Seconds 3
$service = Get-Service -Name "salt-minion"
if ($service.Status -eq "Running") {
    Write-Host ""
    Write-Host "=== Installation Complete ===" -ForegroundColor Green
    Write-Host "Salt Minion is running."
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Yellow
    Write-Host "  1. On the Salt Master, accept the minion key:"
    Write-Host "     salt-key -a $MinionId"
    Write-Host ""
    Write-Host "  2. Test connectivity:"
    Write-Host "     salt '$MinionId' test.ping"
    Write-Host ""
} else {
    Write-Error "Salt Minion service failed to start. Check logs at C:\salt\var\log\salt\minion"
    exit 1
}
