# Configures salt-minion to push job returns to MongoDB
# Credentials come from pillar (generated by master entrypoint, never in git)
# Schedule: common.scheduler runs this state every 60 min to keep config fresh

include:
  - linux.returners
  - windows.returners
