#!jinja|yaml
# MongoDB returner config — credentials generated by entrypoint, never in git
{% set data_dir = '/srv/data/mongo' %}
{% set pass_file = data_dir ~ '/password' %}
{% set host_file = data_dir ~ '/host' %}
{% set mongo_pass = salt['file.read'](pass_file) | trim if salt['file.file_exists'](pass_file) else '' %}
{% set mongo_host = salt['file.read'](host_file) | trim if salt['file.file_exists'](host_file) else 'mongo' %}

mongo.host: {{ mongo_host }}
mongo.port: 27017
mongo.db: salt
mongo.user: salt
mongo.password: {{ mongo_pass }}
mongo.authdb: admin
