beacons:

  salt_file_roots:
    - files:
        /provisioning:
          mask:
            - modify
        /srv/salt:
          mask:
            - modify
    - beacon_module: inotify

  salt_keys:
    - files:
      /etc/salt/pki/api/salt.key:
        mask:
          - modify
      /etc/salt/pki/api/salt.crt:
        mask:
          - modify
    - beacon_module: inotify
