memcache_expire_seconds: 900
memcache_max_items: 512
preserve_minion_cache: True

pillar_cache: False
pillar_cache_ttl: 900
pillar_cache_backend: memory

master_job_cache: local_cache
cache: mmap_cache
keep_jobs: 2
# ext_job_cache

con_cache: True

minion_data_cache: True
enforce_mine_cache: False
