log_granular_levels:
  'salt': 'error'
  'salt.modules': 'info'
  'salt.loaded.ext.module.custom_module': 'warning'
  'salt.loaded.ext.states.custom_module': 'warning'
  'salt.utils.schedule': 'error'
  'salt.beacons': 'error'
