# https://docs.saltproject.io/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html
rest_cherrypy:

  # Opts
  debug: True

  # Listen
  port: 3333
  host: 0.0.0.0

  # TLS — cert generated via orch.gen-api-cert on master minion startup
  ssl_crt: /etc/salt/pki/api/salt.crt
  ssl_key: /etc/salt/pki/api/salt.key
