# https://docs.saltproject.io/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html
rest_cherrypy:

  # Opts
  debug: True

  # Listen
  port: 3333
  host: 0.0.0.0

  # Cert paths & Usage

  ## if cert
  #ssl_crt: /path/to/ssl.crt
  #ssl_key: /path/to/ssl.key

  ## Else disable
  disable_ssl: true

  # SaltGUI
  app: /saltgui/index.html
  static: /saltgui/static
  static_path: /static
