# https://wiki.archlinux.org/title/SDDM
[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
GreeterEnvironment=PATH=/usr/bin:/usr/lib:/bin,QML2_IMPORT_PATH=/usr/lib/qt/qml,QT_WAYLAND_SHELL_INTEGRATION=layer-shell,QT_SCREEN_SCALE_FACTORS=0.5,QT_FONT_DPI=48
DisplayServer=wayland

[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1 --inputmethod plasma-keyboard
EnableHiDPI=false

[X11]
EnableHiDPI=false

[Users]
HideShells=/usr/bin/nologin,/sbin/nologin,/bin/nologin,/bin/false,/usr/bin/git-shell
MinimumUid=500

[Theme]
Current=sddm-astronaut-theme
EnableAvatars=true

