# define cache dir

export CONDA_PKGS_BASE="${TMPDIR}/cache/miniforge"
export CONDA_PKGS_DIRS="${CONDA_PKGS_BASE}/${UID:-$(id -u)}"

# .envrc auto update conda envs ( 0 disabled ; 1 enabled )
export __CONDA_UPDATE="0"
