# Disable pip cache w 1 to save space
# shellcheck disable=SC2034
PIP_NO_CACHE_DIR="${PIP_NO_CACHE_DIR:-1}"

# Define conda/pip cache dir paths
# shellcheck disable=SC2034
PIP_CACHE_DIR="${TMPDIR}/pip-cache"

# Prevent .pyc files and __pycache__
PYTHONDONTWRITEBYTECODE="1"
