# Disable pip cache w 1 to save space
# shellcheck disable=SC2034
export PIP_NO_CACHE_DIR="${PIP_NO_CACHE_DIR:-1}"

# Define /pip cache dir paths
# shellcheck disable=SC2034
export PIP_CACHE_BASE="${TMPDIR}/cache/pip"
export PIP_CACHE_DIR="${PIP_CACHE_BASE}/${UID:-$(id -u)}"

# Prevent .pyc files and __pycache__
export PYTHONDONTWRITEBYTECODE="1"
