# https://man.archlinux.org/man/systemd-sleep.conf.5
# https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate

[Sleep]
MemorySleepMode=deep
SuspendState=mem
AllowHibernation=no
AllowHybridSleep=no
AllowSuspendThenHibernate=no
SuspendState=mem
MemorySleepMode=deep